Update feed [ iopsys ]
-------------------------------------------------------------------------------
* f43f8fd9 dectmngr: Fix for setting model-id in DCX81
-------------------------------------------------------------------------------
commit f43f8fd9662baa5ef3799bb003259e7cb20a360b
Author: Grzegorz Sluja <grzegorz.sluja@sigma.se>
Date: 2022-03-16 12:41:10 +0100

    dectmngr: Fix for setting model-id in DCX81

    2869a87 Fix undefined reference to LOG_DECT_DEBUG when
    ENABLE_DECTMNGR_DEBUG=1 b91368e Restart CMBS target after model-id is
    changed

Base directory -> feeds/iopsys/
 dectmngr/Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
-------------------------------------------------------------------------------