Update feed [ airoha ]
-------------------------------------------------------------------------------
* b4ab1657 Added new musl objects for PON
* 0645f61e Fix path accessing ecnt-function.mk in xpon_bsp
* b1bc7e0f Fix compilation error: xdsl_cmd
* 28f9f182 Revert "iopsys-econet: disabled PON compilation issue"
-------------------------------------------------------------------------------
commit b4ab1657b70ebba28a25a92e029c1d4aab982195
Author: Lukasz Kotasa <lukasz.kotasa@iopsys.eu>
Date: 2022-11-02 13:31:51 +0100

    Added new musl objects for PON

    Also some header changes in:
     modified:   BSP/xpon_bsp/src/app_bsp/xpon_lib/pon_vlan/lib_pon_vlan.h
     modified:   BSP/xpon_bsp/src/app_bsp/xpon_lib/xpon_blapi/blapi_xpon.h

    Source of files: file:
    draft_openwrt-airoha-feeds-sdk_for_7529_7915_musl.tar.gz sha256sum:
    7cf72478d96ed2341929c332fd7351f5a1b2516e6a58fffa85fa3e4e64b5807c link:
    https://project.iopsys.eu/dmsf/files/1332/view

Base directory -> feeds/airoha/
 .../oam/src/oam/epon_oam.o                         | Bin 41156 -> 42636 bytes
 .../oam/src/oam/epon_oam_dbg_srv.o                 | Bin 7776 -> 7492 bytes
 .../oam/src/oam/epon_oam_timer.o                   | Bin 12492 -> 12308 bytes
 .../oam/src/oam/epon_oam_util.o                    | Bin 2160 -> 2216 bytes
 .../omci/src/omci_adpt/omci_adpt_gpon_flow.o       | Bin 11860 -> 11976 bytes
 .../omci/src/omci_frame/omci.o                     | Bin 66412 -> 67944 bytes
 .../omci/src/omci_frame/omci_dbg_func.o            | Bin 23812 -> 23868 bytes
 .../omci/src/omci_frame/omci_general_func.o        | Bin 57440 -> 60088 bytes
 .../omci/src/omci_frame/omci_me.o                  | Bin 78292 -> 80404 bytes
 .../omci/src/omci_frame/omci_message_handle.o      | Bin 3304 -> 3388 bytes
 .../omci/src/omci_frame/omci_reinit_mibupload.o    | Bin 13324 -> 13696 bytes
 .../omci/src/omci_frame/omci_timer.o               | Bin 9772 -> 9596 bytes
 .../omci/src/omci_frame/omci_utily.o               | Bin 6400 -> 7004 bytes
 .../xpon_cmd/epon/eponcmd.o                        | Bin 14160 -> 14152 bytes
 .../xpon_cmd/eponmap/eponmapcmd.o                  | Bin 10628 -> 10624 bytes
 .../xpon_cmd/gponmap/gponmapcmd.o                  | Bin 8340 -> 8340 bytes
 .../xpon_cmd/pon_mac_filter/ponmacfiltercmd.o      | Bin 6284 -> 6232 bytes
 .../xpon_cmd/pon_vlan/ponvlancmd.o                 | Bin 29324 -> 29392 bytes
 .../xpon_cmd/ponmgrcmd/eponmgr.o                   | Bin 20404 -> 20372 bytes
 .../xpon_cmd/ponmgrcmd/gponmgr.o                   | Bin 77036 -> 77008 bytes
 .../xpon_cmd/ponmgrcmd/ponmgrcmd.o                 | Bin 2752 -> 2760 bytes
 .../xpon_cmd/ponmgrcmd/xgponmgr.o                  | Bin 33540 -> 33532 bytes
 .../xpon_cmd/xpon_blapi_cmd/xpon_blapi_cmd.o       | Bin 9112 -> 9120 bytes
 .../xpon_cmd/xpon_cmd_general.o                    | Bin 2220 -> 2232 bytes
 .../xpon_cmd/xpon_igmp/xponigmp_cmd.o              | Bin 24968 -> 24952 bytes
 .../xpon_lib/epon/libepon.o                        | Bin 10468 -> 10972 bytes
 .../xpon_lib/eponmap/libeponmap.o                  | Bin 4560 -> 4776 bytes
 .../xpon_lib/gponflow/gpon_flow_lib.o              | Bin 1936 -> 2064 bytes
 .../xpon_lib/gponmap/libgponmap.o                  | Bin 4304 -> 4304 bytes
 .../xpon_lib/pon_mac_filter/lib_pon_mac_filter.o   | Bin 5060 -> 5224 bytes
 .../xpon_lib/pon_vlan/lib_pon_vlan.o               | Bin 27724 -> 27988 bytes
 .../xpon_lib/ponmgr/api_lib_eponmgr.o              | Bin 25920 -> 26360 bytes
 .../xpon_lib/ponmgr/api_lib_gponmgr.o              | Bin 90900 -> 91184 bytes
 .../xpon_lib/ponmgr/api_lib_xgponmgr.o             | Bin 16312 -> 16496 bytes
 .../xpon_lib/xpon_blapi/blapi_xpon.o               | Bin 13592 -> 12564 bytes
 .../xpon_lib/xpon_igmp/lib_xpon_igmp.o             | Bin 14460 -> 16824 bytes
 .../xpon_lib/xpon_igmp/xpon_igmp_omci.o            | Bin 6028 -> 6172 bytes
 .../src/app_bsp/xpon_lib/pon_vlan/lib_pon_vlan.h   |  16 ++++++++--------
 .../src/app_bsp/xpon_lib/xpon_blapi/blapi_xpon.h   |   4 ++--
 .../CpuPower.ko                                    | Bin 102316 -> 102056 bytes
 .../thermal.ko                                     | Bin 94188 -> 91492 bytes
 .../gpon_flow.ko                                   | Bin 1169032 -> 1166752 bytes
 .../hw_nat.ko                                      | Bin 2275960 -> 2263032 bytes
 .../ifc.ko                                         | Bin 643676 -> 643120 bytes
 .../ponmacfilter.ko                                | Bin 100836 -> 100652 bytes
 .../ponvlan.ko                                     | Bin 439956 -> 439544 bytes
 .../sif.ko                                         | Bin 280952 -> 280500 bytes
 .../xpon_igmp.ko                                   | Bin 612384 -> 611940 bytes
 .../xpon_int.ko                                    | Bin 52812 -> 52652 bytes
 .../xponmap.ko                                     | Bin 303368 -> 303040 bytes
 50 files changed, 10 insertions(+), 10 deletions(-)
-------------------------------------------------------------------------------
commit 0645f61e60cb04fc33c03297d9d5e8af7e68d54e
Author: Lukasz Kotasa <lukasz.kotasa@iopsys.eu>
Date: 2022-11-02 13:30:41 +0100

    Fix path accessing ecnt-function.mk in xpon_bsp

Base directory -> feeds/airoha/
 BSP/xpon_bsp/src/make_xpon_bsp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
-------------------------------------------------------------------------------
commit b1bc7e0fe7ef363ba994477c9644cb48c4deea72
Author: Lukasz Kotasa <lukasz.kotasa@iopsys.eu>
Date: 2022-11-02 13:27:28 +0100

    Fix compilation error: xdsl_cmd

    xdsl_cmd was not delivered in any SDK.

Base directory -> feeds/airoha/
 BSP/xpon_app/Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
-------------------------------------------------------------------------------
commit 28f9f182f6a462c8ceb6ec78934987a8c6e06744
Author: Lukasz Kotasa <lukasz.kotasa@iopsys.eu>
Date: 2022-11-02 09:43:04 +0100

    Revert "iopsys-econet: disabled PON compilation issue"

    This reverts commit 28733f83c6fcfe87d6451ab918028c16384cbaf3.

Base directory -> feeds/airoha/
 BSP/xpon_bsp/Makefile | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)
-------------------------------------------------------------------------------