Update feed [ broadcom ] package [ bcmkernel-4.1 ]
-------------------------------------------------------------------------------
* 4dee8682e fix undefined reference to bcm_led_driver_brightness when build soc 63178 (soc 6750)
-------------------------------------------------------------------------------
commit 4dee8682e64d29404d5a8625eb7f23ed2b068f76
Author: Oussama Ghorbel <oussama.ghorbel@iopsys.eu>
Date: 2020-06-22 16:31:25 +0200

    fix undefined reference to bcm_led_driver_brightness when build soc 63178
    (soc 6750)

    The build issue is caused by commit bbf7db19  by implementing the function
    bcm_led_driver_brightness() in
    bcm963xx/shared/opensource/drivers/bcm_led_impl1.c only, instead of
    implementing it in bcm963xx/shared/opensource/drivers/bcm_led_impl4.c as
    well.

Base directory -> /
 bcm963xx/bcmdrivers/opensource/char/board/bcm963xx/impl1/bcm63xx_led.c | 3 +++
 1 file changed, 3 insertions(+)
-------------------------------------------------------------------------------